-- MySQL Script generated by MySQL Workbench
-- Sat Dec 27 14:48:51 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackid` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hackid` ;

-- -----------------------------------------------------
-- Table `hackid`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackid`.`User` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `allergies` VARCHAR(45) NULL,
  `school` VARCHAR(45) NULL,
  `age` INT NULL,
  `rfid` VARCHAR(45) NULL,
  `notes` VARCHAR(500) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
